config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  get '/auth/google_oauth2/callback'=> 'sessions#omniauth'

  resources :users, only: [:show, :new, :create]

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'

  resources :orders
  resources :builds
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ActiveRecord::Base
    belongs_to :job
    belongs_to :location
    belongs_to :status
    include ShopTracking
    extend ShopTracking::ClassMethods
    include ShopTracking::InstanceMethods
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
    belongs_to :truck
end

app/models/job.rb
class Job < ActiveRecord::Base
    has_many :orders
    has_many :builds
    has_many :used_materials
    has_many :materials, through: :used_materials
    
end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :builds
    has_many :orders
end

app/models/material.rb
class Material < ActiveRecord::Base
    has_many :used_materials
    has_many :jobs, through: :used_materials
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :job
    belongs_to :location

    include ShopTracking
    extend ShopTracking::ClassMethods
    include ShopTracking::InstanceMethods
end

app/models/shop_tracking.rb
module ShopTracking 
    MANAGER = ['Joey P', 'Sean S', 'Matt M', 'Tony B', 'Allyson H', 'Rob S', 'Doug G', 'Robbie R']
    FOREMAN = ['Adam S', 'Allen B', 'Chris D', 'Dustin P', 'Jesse S', 'Joel T', 'Josh G','RD L','Marcus P','Mark B', 'Jeff J' ]
    LINER = ['', '0.5 - R2.2', '1.0 - R4.2', '2.0 - R6.3', '1.0 - ArmaFlex','1.5 - ArmaFlex','2.0 - ArmaFlex', '1.0 - K-Flex','Neoprene', 'Spiracoustic']
    DEPT = ['Specialty','Industrial','HVAC','Laser']
    
    module ClassMethods
    end
    module InstanceMethods
    end
end

app/models/status.rb
class Status < ActiveRecord::Base
    has_many :builds
end

app/models/truck.rb
class Truck < ActiveRecord::Base
    has_many :deliveries
end

app/models/used_material.rb
class Used_Material < ActiveRecord::Base
    belongs_to :material
    belongs_to :job
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :current_user

    def current_user
        @current_user = User.find_by(id: session[:user_id])
      end
    
      def logged_in?
        session[:user_id]
      end
    
      def authentication_required                             
        redirect_to root_path unless logged_in?
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

     def home
     end
 
     def new
         @user = User.new
     end

     def omniauth
        binding.pry
     end
     
     def create
         user = User.find_by(email: params[:user][:email])
         @user = user.try(:authenticate, params[:user][:password])
         return redirect_to signin_path unless !@user.nil?
         session[:user_id] = @user.id
         redirect_to user_path(@user)
     end
 
     def destroy
        # binding.pry
         session.delete :user_id
         redirect_to signin_path
     end
 
 
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authentication_required, only: [:show]

    def new
        @user = User.new
    end

    def show
        #binding.pry
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)

        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end

    end

    def destroy
    end

    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :role, :password)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

    
    def show_user_dashboard
        role = @current_user.role

        return tag.p 'I have not been verified as an Employee yet!' unless @current_user.verified

            case role
            when 'Supervisor'
                tag.p 'I can do/view/approve Everything!'
            when 'Lead'
                tag.p 'I can do most things'
                link_to 'Receiving', 
            when 'Project Manager'
                tag.p 'I can only view things'
            when 'Employee'
                tag.p 'I can only add my own things'
            else
                tag.p 'Do NOT know how you got this far without a role.  Go back and get yourself one before continuing'
            end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopProgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
           <h1> Shop Program </h1>
          <div class="nav-bar" style="display:inline;">
            <p> 
              <%= link_to "|___( SIGN UP )___|", new_user_path %> 
              <%= link_to "___( LOG IN )___|", signin_path %>
              <%= link_to "___( LOG OUT )___|", signout_path, method: 'post' %>
            </p>
          </div>
      </header>
      <hr>
      <div class="main_page">
          <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopProgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
           <h1> Shop Program (Users) </h1>
          <div class="nav-bar" style="display:inline;">
            <p> 
              <%= link_to "|___( HOME )___|", user_path(@current_user) %> 
              <%= link_to "___( LOG OUT )___|", signout_path, method: 'post' %>
              [<%= @current_user.role %>] <%= @current_user.first_name %> <%= @current_user.last_name[0].capitalize %> 
            </p>
          </div>
      </header>
      <hr>
      <div class="main_page">
          <%= yield %>
      </div>
  </body>
</html>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_with model: @user do |f| %>

    <%= f.label :first_name %> <br>
    <%= f.text_field :first_name %> <br><br>

    <%= f.label :last_name %> <br>
    <%= f.text_field :last_name %> <br><br>

    <%= f.label :role %> <br>
    <%= f.select :role, ["Supervisor", "Lead", "Project Manager", "Employee"], include_blank: true %> <br><br>

    <%= f.label :email %> <br>
    <%= f.email_field :email %> <br><br>

    <%= f.label :password %>
    <%= f.password_field :password %> <br><br>

    <%= f.submit %>
<% end %>

<br><br>
<%= button_to "Log in with Google", "/auth/google_oauth2"%>

app/views/users/show.html.erb
<h2>User show Page</h2>

<%= show_user_dashboard %>